version: '3.9'

services:
  database:
    image: postgres
    container_name: database_feedify
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=feedify
      # - db_host=database
    volumes:
      - pgdata:/data/postgres
    ports:
      - "5432:5432"
    restart: always

  # app:
  #   build: .
  #   container_name: feedify
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
